# This is second file
print('Test')
print('adding new line')
print('Fixing bug')
print('Code changes')
print('This change is from new cloned repo')
print('Additional changes to test sqash merge')
print('on branch newone')
print('This is a major fix')
print('another hotfix')
print('These changes are for newChanges1 branch')
print('These changes are from newChanges3 branch')
